### ISSUE TITLE
AttributeError: module 'numpy.typing' has no attribute 'NDArray' 

### ISSUE THREAD

**Issue by shayneoneill** [axelande/geodatafarm#6] opened 2024-07-10 04:54 UTC
Computer: MacOS
Version of QGIS: 3.28.0 Grenoble 

Error AttributeError: module 'numpy.typing' has no attribute 'NDArray' 

The first error I came across was about reportlab being installed. After some messing about I managed to install it via 

/Applications/QGIS.app/Contents/MacOS/bin/python3.9 -m pip install reportlab

After that I get this numpy error.

The problem is, if I upgrade numpy using the --force option, it upgrades to version 2.0 which basically completely breaks qgis.

Some guidance on fixing this would be appreciated.

**Comment by axelande** [comment] 2024-09-25 04:24
Sorry for the superlate respons! If you have not solved the issue you can install run "pip install numpy<2" (based on other that have had the same issue it have been resolved by reinstalling numpy)

**Comment by shayneoneill** [comment] 2024-09-25 13:25
Ok. Did that now I get 

ImportError: cannot import name 'broadcast_to' from 'numpy.lib.stride_tricks' (/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy/lib/stride_tricks.py)

**Comment by axelande** [comment] 2024-09-27 05:12
So strange, I have no idea why your numpy package have these issues, it is one of the most used python packages. I don't have a mac so I can't help you debug it (but I know that many mac users have used the plugin..)

Since the issue is in numpy I would suggest to run "pip uninstall numpy", "pip install numpy<2" if that doesn't work try to install an older version of numpy "pip install numpy<1.26"

**Closed as completed** 2024-10-18 02:44 UTC
